global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whatsapp-chatbot'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'whatsapp-chatbot'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 